# Generated by Django 3.0.5 on 2020-08-01 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0046_auto_20200731_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_states', models.CharField(default=None, max_length=50, null=True)),
                ('s_count', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='beneficiary_register',
            name='u_edu',
            field=models.CharField(choices=[('10th pass', '10th pass'), ('12th pass', '12th pass'), ('Graduate', 'Graduate'), ('Below 10th', 'Below 10th')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary_register',
            name='u_ration',
            field=models.CharField(choices=[('Yellow', 'Yellow'), ('Orange', 'Orange'), ('White', 'White')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userbmi',
            name='bmdate',
            field=models.DateField(default=datetime.date(2020, 8, 1)),
        ),
    ]
