# Generated by Django 3.0.5 on 2020-07-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0007_auto_20200704_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary_register',
            name='u_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiary_register',
            name='u_verified',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
