# Generated by Django 3.0.7 on 2020-07-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0008_auto_20200704_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary_register',
            name='u_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary_register',
            name='u_verified',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
