# Generated by Django 3.0.7 on 2020-07-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0009_auto_20200704_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary_register',
            name='u_addr',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
