# Generated by Django 3.0.5 on 2020-07-07 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0011_auto_20200706_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='userbmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmdate', models.DateField(default=datetime.date.today)),
                ('currentbmi', models.FloatField(max_length=13)),
                ('bmweight', models.FloatField(max_length=13)),
                ('bmheight', models.FloatField(max_length=13)),
                ('bmblood', models.FloatField(max_length=13)),
                ('bmuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiary.beneficiary_register')),
            ],
        ),
    ]
