# Generated by Django 3.0.5 on 2020-07-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0012_userbmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='userappointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apdate', models.DateField()),
                ('apno', models.IntegerField(max_length=13)),
                ('apstatus', models.BooleanField(default=False)),
                ('apid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiary.beneficiary_register')),
            ],
        ),
    ]
