# Generated by Django 3.0.5 on 2020-07-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0014_auto_20200709_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbmi',
            name='bmuser',
        ),
        migrations.AddField(
            model_name='userbmi',
            name='bmid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userappointments',
            name='apstatus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userbmi',
            name='bmblood',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userbmi',
            name='bmdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userbmi',
            name='bmheight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userbmi',
            name='bmweight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userbmi',
            name='currentbmi',
            field=models.FloatField(null=True),
        ),
    ]
