# Generated by Django 3.0.5 on 2020-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0017_auto_20200709_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappointments',
            name='apstatus',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
