# Generated by Django 3.0.5 on 2020-07-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0018_auto_20200709_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbmi',
            name='bmuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiary.beneficiary_register'),
        ),
    ]
