# Generated by Django 3.0.5 on 2020-07-11 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0022_auto_20200710_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbmi',
            name='bmdate',
            field=models.DateField(default=datetime.date(2020, 7, 11)),
        ),
    ]
