# Generated by Django 3.0.5 on 2020-07-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0023_auto_20200711_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappointments',
            name='apref',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
