# Generated by Django 3.0.5 on 2020-07-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0024_userappointments_apref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbmi',
            name='bmworker',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
