# Generated by Django 3.0.5 on 2020-07-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0029_auto_20200713_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappointments',
            name='apPincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
