# Generated by Django 3.0.5 on 2020-07-19 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0033_auto_20200716_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbmi',
            name='bmdate',
            field=models.DateField(default=datetime.date(2020, 7, 19)),
        ),
    ]
