# Generated by Django 3.0.5 on 2020-07-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0035_auto_20200725_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary_register',
            name='u_DOB',
            field=models.DateField(null=True),
        ),
    ]
