# Generated by Django 3.0.7 on 2020-07-26 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0036_beneficiary_register_u_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary_register',
            name='u_phone',
            field=models.CharField(default=None, max_length=13),
        ),
        migrations.AddField(
            model_name='beneficiary_register',
            name='u_type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userbmi',
            name='bmdate',
            field=models.DateField(default=datetime.date(2020, 7, 26)),
        ),
    ]
