# Generated by Django 3.0.7 on 2020-07-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0038_auto_20200726_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary_register',
            name='u_phno',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
    ]
