# Generated by Django 3.0.7 on 2020-07-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0039_auto_20200726_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappointments',
            name='u_user_id',
            field=models.CharField(default=None, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='userbmi',
            name='u_user_id',
            field=models.CharField(default=None, max_length=14, null=True),
        ),
    ]
