# Generated by Django 3.0.7 on 2020-07-27 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0042_userappointments_aptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbmi',
            name='bmdate',
            field=models.DateField(default=datetime.date(2020, 7, 27)),
        ),
    ]
