# Generated by Django 3.0.5 on 2020-07-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0043_auto_20200727_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary_register',
            name='u_phno',
            field=models.CharField(blank=True, default=None, max_length=13, null=True, unique=True),
        ),
    ]
