# Generated by Django 3.0.5 on 2020-07-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0044_auto_20200727_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary_register',
            name='u_father',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='beneficiary_register',
            name='u_mother',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
