# Generated by Django 3.0.5 on 2020-07-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker_register',
            name='district',
        ),
        migrations.RemoveField(
            model_name='worker_register',
            name='user',
        ),
        migrations.AddField(
            model_name='worker_register',
            name='hw_district',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='worker_register',
            name='hw_fname',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='worker_register',
            name='hw_password',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='worker_register',
            name='hw_sname',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='worker_register',
            name='hw_adhar',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='worker_register',
            name='hw_phno',
            field=models.CharField(default=None, max_length=13),
        ),
        migrations.AlterField(
            model_name='worker_register',
            name='hw_pincode',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
