# Generated by Django 3.0.5 on 2020-07-03 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0002_auto_20200703_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker_register',
            name='hw_password',
        ),
        migrations.AddField(
            model_name='worker_register',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
