# Generated by Django 3.0.5 on 2020-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200703_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_register',
            name='hw_password',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
