# Generated by Django 3.0.7 on 2020-07-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_remove_worker_register_hw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_register',
            name='hw_addr',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
